### ISSUE TITLE
1.12.2 Can't run or build,don‘t know why

### ISSUE THREAD

**Issue by AntiThesis1250** [TimeConqueror/Time-Core#2]
![image](https://user-images.githubusercontent.com/31405319/146668911-b412aa6a-3e7f-4635-8a1a-10d03bc01ec1.png)
1.12.2 Can't run or build,don‘t know why

**Comment by TimeConqueror** [comment]
The reasons may vary, so it's better to ask it in my discord server https://discord.gg/KVpAJGa with more details
