### ISSUE TITLE
1.16.5 Crash on Startup or Opening ESC menu Essential, ModernFix, and Time Core

### ISSUE THREAD

**Issue by SpecialtyK** [TimeConqueror/Time-Core#5]
A combination of Essential, ModernFix, and Time Core. Created a new instance with just those three mods installed and crashed at the main menu. https://paste.ee/p/Kdybz 
Removing Time Core it no longer crashes. If it doesn't crash at the main menu pressing ESC in game will cause a crash. ModernFix allows me to use Java 17 for 1.16.5 if Java version is the issue.

**Comment by TimeConqueror** [comment]
@SpecialtyK Hi! Thank you for reaching me out! 
I tried to reproduce it with Java17, but no crash appeared. Installed mods: Essintial Forge 1.16.5 of Aug 5 2022, modernfix-mc1.16.5-1.11.2, TimeCore-1.16.5-3.5.0.0
![image](https://user-images.githubusercontent.com/25156941/231308457-3f2186bb-f8a8-46ba-bf7a-4fd49330747b.png)

**Comment by SpecialtyK** [comment]
Hmmm, odd neither could the creator of Modernfix. The only other thing is I am using these java arguments as suggested on the ModernFix page to supposedly make mods more compatible with Java 17 on 1.16.5 through the MultiMC launcher. 

-XX:+ExplicitGCInvokesConcurrent -Djava.security.manager=allow -Dfile.encoding=UTF-8 --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED,java.naming --add-opens java.desktop/sun.awt.image=ALL-UNNAMED --add-modules jdk.dynalink --add-opens jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED --add-modules java.sql.rowset --add-opens java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED --add-exports java.base/sun.security.util=ALL-UNNAMED --add-opens java.base/java.util.jar=ALL-UNNAMED -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M

**Comment by SpecialtyK** [comment]
Talking with someone at Essential said the issue is not being able to convert the time to a friendlier format to display on the sale banner.  Nobody else was able to reproduce the crash because when tested the sale ended most likely.
